require('config.colorscheme')
require('config.autopairs')
--require('config.completion')
require('config.fugitive')
require('config.ident_blankline')
-- require('config.lualine')
require('config.gitsigns')
require('config.maximizer')
require('config.nerdcommenter')
require('config.nerdtree')
require('config.translate')
require('config.telescope')
require('config.cmp')
require('config.toggleterm')
require('config.vimwiki')
require('config.glow')

