require('config.colorscheme')
require('config.autopairs')
require('config.autosave')
--require('config.completion')
require('config.fugitive')
require('config.ident_blankline')
require('config.lualine')  --kkk
require('config.gitsigns')
require('config.marks')
require('config.maximizer')
-- require('config.nerdcommenter')
require('config.nerdtree')
require('config.translate')
require('config.telescope')
require('config.cmp')
require('config.nvim-snippy')
require('config.toggleterm')
require('config.vimwiki')
require('config.glow')

